"""Implementar un programa en Python que pida al usuario que ingrese dos 
números y muestre la suma, resta, división y multiplicación de ambos."""

NUMERO1 = float(input("Ingrese el primer numero: "))
NUMERO2 = float(input("Ingrese el segundo numero: "))

print(f"La suma de ambos es: {NUMERO1+NUMERO2}")
print(f"La multiplicaciòn de ambos es: {NUMERO1*NUMERO2} ")
print(f"La division de ambos es: {NUMERO1/NUMERO2}")
print(f"La resta de ambos es: {NUMERO1-NUMERO2}")